# Generated by Django 5.0.1 on 2024-06-08 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Books',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='NULL', max_length=122)),
                ('subject', models.CharField(default='NULL', max_length=122)),
                ('author', models.CharField(default='NULL', max_length=10)),
                ('quantity', models.IntegerField(default=1, max_length=100)),
                ('isBorrowed', models.BooleanField(default=False)),
            ],
        ),
    ]
